### ISSUE TITLE
Display Mising work

### ISSUE THREAD

**Issue by Tiske1964** [loujine/musicbrainz-scripts#10]
Hi

Display Missing work does not work anymore. I also don't see the button anymore. Checked for updates and there werent any. 

Working with Firefox

Hope you understand what I mean my english is very bad

ty for this wonderful addon Now im feeling sad

Love
Tis

**Comment by loujine** [comment]
The MusicBrainz website update yesterday removed a library all scripts were depending on, reo fixed it with PR #9.

Update your scripts to version 2020.9.8 and it should work again. There was also something wrong with the update system for this script, it should be fixed now. Tell me if the update still fails for you.

PS: nothing wrong with your english, I understood it all
