### ISSUE TITLE
Scripts won't display.

### ISSUE THREAD

**Issue by translit** [loujine/musicbrainz-scripts#12]
Continued from https://github.com/loujine/musicbrainz-scripts/pull/9#issuecomment-690146440

@loujine: Thanks, Jérôme.

> what version of the scripts do you have?

Scripts 2020.9.8, 2020.9.8.1
Tampermonkey 4.11.6117
Safari 13.1.2
macOS 10.14.6

> what error message can you see in the console?

```
[Error] Syntax error @ "MusicBrainz edit: Create entity or fill data from wikipedia / wikidata / VIAF / ISNI"!
##########################
JSHINT output:
##########################

eval@[native code]
https://musicbrainz.org/artist/foobar
c@https://musicbrainz.org/artist/foobar
https://musicbrainz.org/artist/foobar
na
create
d
runListeners

P@https://musicbrainz.org/artist/foobar
dispatchEvent@[native code]
send@safari-extension://5834CAFB-16E5-4929-8B50-99BF49DD63EB/6fd470cf/content.js:7:278
safari-extension://5834CAFB-16E5-4929-8B50-99BF49DD63EB/6fd470cf/content.js:27:157
processQueue@safari-extension://5834CAFB-16E5-4929-8B50-99BF49DD63EB/6fd470cf/content.js:3:121
a@safari-extension://5834CAFB-16E5-4929-8B50-99BF49DD63EB/6fd470cf/content.js:9:397
	error
	(anonymous function) (Anonymous Script 1 (line 60:378))
	(anonymous function) (Anonymous Script 1 (line 22:150))
	I (Script Element 2:11)
	P (Script Element 2:11:117)
	dispatchEvent
	(anonymous function) (content.js:7:149)
	b (topee-content.js:2277)
```

> If you have a too old version, the upgrade won't work. Reinstall the scripts instead.

Reinstalled. Still no luck.

**Comment by loujine** [comment]
I'll try to find a mac computer and take a look tomorrow

**Comment by loujine** [comment]
I couldn't test from Safari and the error message you have is not clear at all. 
Nevertheless there was a small syntax bug introduced two days ago that firefox doesn't complain about but might be the reason Safari complains. Can you try to test version 2020.9.11?

**Comment by translit** [comment]
Bingo! 2020.9.11 did the trick. The script launches and the console reports no errors. Thank you.

Will you be updating other 2020.9.8's? Two of my favourites, 'Guess related works in batch' and 'Display sort button on table columns', don't function either.

**Comment by loujine** [comment]
That's strange, the bug I solved is specific to the wikidata script. I don't see why the other ones wouldn't work in version 2020.9.8
Can you check if you have other error messages? Where are you installing the scripts from?

**Comment by translit** [comment]
> Can you check if you have other error messages?

Yes. All scripts that are supposed to run on Release > Edit Relationships throw [errors](https://github.com/loujine/musicbrainz-scripts/files/5212181/Console.txt).

> Where are you installing the scripts from?

From here (GitHub). I used to install them from your previous repository (BitBucket?), but then deleted them and installed anew from GitHub.

**Comment by loujine** [comment]
If the other error messages are the same as the one above, I have no idea.
Did you try to disable all other scripts running on this page?

**Comment by translit** [comment]
> If the other error messages are the same as the one above, I have no idea.

I'm now getting this:

````
edit-relationships:6
[Error] SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.
	(anonymous function) (Anonymous Script 1 (line 3:104))
````

> Did you try to disable all other scripts running on this page?

Yes. If we can't fix it, I guess I'd better switch to Firefox for my MusicBrainz work.

**Comment by translit** [comment]
All works now. Can't tell what has changed, though.

**Comment by loujine** [comment]
Glad to hear it

Well, I'm going to pretend it's due to my hard work :p
