### ISSUE TITLE
Copy dates on recording relations broken

### ISSUE THREAD

**Issue by DaveO61** [loujine/musicbrainz-scripts#16]
The userscript 'MusicBrainz relation editor: Copy dates on recording relations'
does not work anymore since the MusicBrainz Server update 2020-09-07.

**Comment by loujine** [comment]
Have you updated the script? It works for me with the script version 2020.9.8 from github

**Comment by DaveO61** [comment]
> 
> 
> Have you updated the script? It works for me with the script version 2020.9.8 from github

I did but have discovered the link has gone so obviously won't update so i will have a look in github

**Comment by loujine** [comment]
Yes, if you have an old version of the scripts from bitbucket or greasemonkey the update won't work

**Comment by DaveO61** [comment]
> 
> 
> Yes, if you have an old version of the scripts from bitbucket or greasemonkey the update won’t work

Yes Thanks all sorted now
