### ISSUE TITLE
Add languages to the add alias script 

### ISSUE THREAD

**Issue by reosarevok** [loujine/musicbrainz-scripts#21]
Hi! Posting on behalf of CatCat who can't access Github.

Requested languages are: 
```
chinese traditional
chinese simplified
singaporean (Chinese Singapore Simplified)
taiwanese (Chinese Taiwan Traditional)
Chinese Hong Kong (Chinese Hong Kong SAR China Traditional)
marathi
kannada
tamil
gujarati
telugu
sinhala
burmese
georgian
Kurdish (Central)
Asturian
Galician
Gaelic
Frisian (Western)
Mongolian
Kyrgyz
Quechua
Interlingua
Somali
Yoruba
Zulu
Filipino
Uyghur
Breton
Faroese
Yiddish
Luxembourgish
Amharic
Low German
```

Also:

> additionally, if it was possible to prepend languages with their two-letter id code (as seen f.ex on the side https://www.wikidata.org/wiki/Q1365218 ) which would let me simply write "es" for spanish, "nn" for nynorsk, "fa" for persian etc. in the language list.

**Comment by loujine** [comment]
Done on branch ff44
