### ISSUE TITLE
Edit Note in new Line

### ISSUE THREAD

**Issue by k-y-a** [loujine/musicbrainz-scripts#25]
Regarding script:

Set guessed works
 —
GM script: "MusicBrainz relation editor: Guess related works in batch"

Hi I'm currently using this script frequently; and these text get add in the Edit note. But it always get add at the end of my current text (I'm also using Elephant memory by jesus2009) which mess up the URL a bit.

Is it possible that this line of text get create/add in a new line? instead of after the latest character. So it currently like this at the moment:

```
Please see: https://musicbrainz.org/Set guessed works
 —
GM script: "MusicBrainz relation editor: Guess related works in batch"
```
Instead can it be like this:

```
Please see: https://musicbrainz.org/
Set guessed works
 —
GM script: "MusicBrainz relation editor: Guess related works in batch"
```

**Comment by loujine** [comment]
That's a good point, I also get bitten by this behavior sometimes.
I'll try to check other scripts to have a unified behavior

Thanks for the suggestion

**Comment by loujine** [comment]
My latest change should fix the problem. You will need to update the "Guess work" script, that should pull the new mbz-loujine-common file at the same time (2020.11.5)
