### ISSUE TITLE
Alias Count (Group same type)

### ISSUE THREAD

**Issue by k-y-a** [loujine/musicbrainz-scripts#26]
Regarding: mb-display_count_alias.user.js 

Test URL: https://musicbrainz.org/artist/89ad4ac3-39f7-470e-963a-56509c546377

I guess for most artist it is fine but I was just at the Various Artist page and the scrollbar vertical is huge.Would it be a better idea to group same type?

For example:
da(4)
en(15)
es(5)

Rather than the current
da,da,da,da,en,en,en... es,es,es,es,es

**Comment by loujine** [comment]
It would make sense, I'll take a look next week

**Comment by loujine** [comment]
Just simplified the code to write each locale only once, which seems a straightforward answer. Thanks for the report, I'm not having this script active most of the time so I never realized
