### ISSUE TITLE
Bug in Mark recordings as video: strips off everything after the ";" in a disambiguation

### ISSUE THREAD

**Issue by vzell** [loujine/musicbrainz-scripts#36]
![image](https://user-images.githubusercontent.com/1648084/115145285-103a8d80-a051-11eb-98bd-b6c0105008b6.png)

This user script strips off everything after the ";" in a disambiguation .. see screenshot above

**Comment by loujine** [comment]
Thanks. It seems that I don't need to edit the disambiguation field at all, so that should be fixed now
