### ISSUE TITLE
[display split recordings] Does not work on non classical works

### ISSUE THREAD

**Issue by jesus2099** [loujine/musicbrainz-scripts#37]
Sub works with no artist relationships: https://musicbrainz.org/work/8f32fb44-fde9-4e44-ad54-d7ac12703b4f
The recording table remains empty.

I am completely clueless with ES6 syntax so I tried really hard but really could not help with a PR.
You should include `inc=artist-credits` too and `props['artists']` should get the recording list of artists from `json["artist-credit"]`.

https://github.com/loujine/musicbrainz-scripts/blob/333a5f7c0a55454080c730b0eb7a22446d48d371/mb-display_split_recordings.user.js#L63-L85

**Comment by loujine** [comment]
I'll try to take a look over the weekend and see if I can remember how this works :)
I might also try to use the first-release-date field to find group sub-recordings together

**Comment by loujine** [comment]
Indeed this seems like the logical solution. This should be fixed now on your example
