### ISSUE TITLE
Wikidata importer: Duplicate links are no longer detected

### ISSUE THREAD

**Issue by kellnerd** [loujine/musicbrainz-scripts#39]
[MBS-11680: Group editing URL relationships by external link](https://tickets.metabrainz.org/browse/MBS-11680) changes the URL releationship editor in a way that the userscript no longer detects whether a link is already existing and leads to lots of duplicates.
Currently this ticket is in beta testing but soon this will also affect the main server.

**Comment by loujine** [comment]
Thanks for the report. I have a fix ready but I probably won't be able to push it on github before Tuesday

**Comment by kellnerd** [comment]
Thank you, I just tested the new version and it is working as expected. I think you can merge this into master now, MBS beta has been released into production yesterday.

**Comment by loujine** [comment]
Thanks @kellnerd !
