### ISSUE TITLE
Lean display: Props <script> for div.release-events-container not found

### ISSUE THREAD

**Issue by yvanzo** [loujine/musicbrainz-scripts#40]
From <https://tickets.metabrainz.org/browse/MBS-11923> it seems that the script `mb-display_lean_ui.user.js` is causing an error when hydrating the release events `div`container in MB release pages. It seems to happen with Firefox (on Windows) only, not Chrome.

**Comment by jesus2099** [comment]
I had this `Error: Props <script>` or something something error too with Vivaldi.

**Comment by loujine** [comment]
Probably due to the script not waiting for the page to be loaded before running
