### ISSUE TITLE
musicbrainz.org/artist/*/releases

### ISSUE THREAD

**Issue by karpuzikov** [loujine/musicbrainz-scripts#42]
please make this script work on
musicbrainz.org/artist/*/releases

**Comment by loujine** [comment]
Which script are you talking about?

**Comment by karpuzikov** [comment]
oh, sorry
mb-display_sortable_table.user.js

**Comment by loujine** [comment]
Should be working in version 2021.9.18

**Comment by karpuzikov** [comment]
it's kinda don't work, for ex. on this page https://musicbrainz.org/artist/65f4f0c5-ef9e-490c-aee3-909e7ae6b2ab/releases

when i click on "format" table, it is sorts by some random

**Comment by loujine** [comment]
Looks ok on my machine. Can you check the web tools consoleqnd see if you get error messages?

**Comment by karpuzikov** [comment]
i tried this on some artist's pages, and on some it works on another don't
don't work https://musicbrainz.org/artist/29266b3d-b5ae-4d09-b721-326246adf68f/releases

works fine https://musicbrainz.org/artist/c137d8be-f60f-4487-a860-f1ecbe06e192/releases
i capture it on video
https://www.youtube.com/watch?v=Ytq93Qd8w5A

**Comment by loujine** [comment]
Can you check with other userscripts disabled? Maybe the "Relationship" column is messing things up

**Comment by loujine** [comment]
Found a bug that was not visible in firefox and that looks a lot like this one, let's hope my patch fixes it
