### ISSUE TITLE
Mark recordings as video: Edit has no edit note

### ISSUE THREAD

**Issue by dgasaway** [loujine/musicbrainz-scripts#47]
The edits created by the script never have an edit note, even if I type my own in the box.  [Example](https://musicbrainz.org/edit/83499394)
![Screenshot_20211011_135549](https://user-images.githubusercontent.com/566661/136854621-310560fe-dc92-44b6-ac01-855ad24e2043.png)

**Comment by loujine** [comment]
Should be fixed now (2021.10.30)
e.g. https://test.musicbrainz.org/edit/79711779
