### ISSUE TITLE
Sort name bug with mb-edit-create_from_wikidata.user

### ISSUE THREAD

**Issue by Fabe56** [loujine/musicbrainz-scripts#48]
Hi,

When copy/paste a VIAF external link, the script also changes the sort name when is for example "The Surname, Fistname" to "Surname, Firstname The". As an example, is often more explicit: [edit 85733754](https://musicbrainz.org/edit/85733754).

Thanks to mr_maxis for notice this ;)

**Comment by loujine** [comment]
Looks like I prevented that behavior only with wikidata links, not VIAF. I will try to fix this
