### ISSUE TITLE
`additional` attribute not selecable in "set role in recording-artist relation"-userscript

### ISSUE THREAD

**Issue by vzell** [loujine/musicbrainz-scripts#52]
I try to fix an artist role reference in the following release https://musicbrainz.org/release/fc86273e-2e9d-4144-81cd-6142f594d272/edit-relationships

additional _mixer_: Danielle Warman
 ==>
additional _engineer_: Danielle Warman

![image](https://user-images.githubusercontent.com/1648084/148681648-af16cd1e-f0fd-4dbd-9875-581310fce727.png)

But it's not possible to select the "**additional**" attribute

**Comment by loujine** [comment]
So it's a bit tricky but I have a solution for you. I don't think I will publish a new version though unless there are more demands for it.

 * you need to replace one line in the script: on line 22 replace `const attrInfo = server.getInstrumentRelationshipAttrInfo();` by `const attrInfo = server.getRelationshipAttrInfo();`.
 * enter manually the value `1` (= the "additional" attribute) in the text boxes for the id

This should select only the additional mixer and convert to additional engineer

Hope this helps

**Comment by vzell** [comment]
Works like a charm ... thx
But will the standard functionality be lost with this change ?

**Comment by loujine** [comment]
No that should still work the same

**Comment by vzell** [comment]
This workaround does not work anymore with the latest version ... is there another trick to choose attributes like "additional", "associate", "assistant" etc. ?
