### ISSUE TITLE
Set work attributes from the composer Work page: Identifier attributes are lost

### ISSUE THREAD

**Issue by yindesu** [loujine/musicbrainz-scripts#53]
The script only handles Type, Lyrics Language, and Key (attribute), therefore deleting any Identifier (attribute) values.

**Comment by jesus2099** [comment]
Hey this sounds like an emergency!
Do you still have some links to edits showing this behaviour?

**Comment by mihawk90** [comment]
I just ran into this, here are some edits:

https://musicbrainz.org/edit/94871712
https://musicbrainz.org/edit/94871664
https://musicbrainz.org/edit/94871701
https://musicbrainz.org/edit/94871663
https://musicbrainz.org/edit/94871644

**Comment by loujine** [comment]
It should be fixed now.
I went through the whole edit history and there was only one edit where the error was not detected
