### ISSUE TITLE
Release timeline prevents MB menu to show up

### ISSUE THREAD

**Issue by jesus2099** [loujine/musicbrainz-scripts#6]
I cannot open MB menus if the script is running on https://musicbrainz.org/artist/0383dadf-2a4e-4d10-a46a-e9e041da8eb3 (or any other artist page).
On https://musicbrainz.org it's OK, because the script is not running there.

**Comment by jesus2099** [comment]
**Error: No container provided**

    if (!container) throw new Error('No container provided');

Called by:

https://github.com/loujine/musicbrainz-scripts/blob/ba5abcb2903ebcb29f1fc77a40c1f2f8ebaa6521/mbz-release_timeline.user.js#L91

**Comment by loujine** [comment]
Sorry, haven't had time to take a look yet, I'll try this weekend

**Comment by loujine** [comment]
There was at least a problem with the selector, tell me if it's better. But I consider this script to be a draft for a server-side solution, so I don't expect this script to be as solid as others. Do you think the functionality is useful?

**Comment by jesus2099** [comment]
Thanks Loujine, there is no crash now, and I see a Timeline entry.
When I click it, a blank zone opens with nothing inside (as you say it's only experimental), but at least, there is no more crash. :)

**Comment by loujine** [comment]
I made some changes this morning, the timeline using vis should be collapsed by default (click "> timeline" to expand it) and carousel should be visible for each type of release groups (using slick-carousel).
Works for me with firefox + tampermonkey

**Comment by jesus2099** [comment]
I tried Vivaldi 3, Firefox 68 and 79, but all I see after clicking Timeline, is an empty zone.

**Comment by loujine** [comment]
Weird. I haven't really looked at how greasemonkey loads data from cdnjs, maybe some network requests are blocked for you? Nothing in the console?

**Comment by loujine** [comment]
Does https://loujine.github.io/musicbrainz-dataviz/1-timelines_visjs.html work for you?

**Comment by jesus2099** [comment]
Yes, this page works, on Firefox for Android 68 with Violentmonkey.
MBS does not respond at the moment. 🤔
Just a small remark also, you should maybe add a `cursor: pointer` style to the Timeline link.

**Comment by jesus2099** [comment]
You actually fixed this ticket issue (blocked MBS menu issue).

---

## Off topic
Now MBS works and the Timeline link just opens a blank area, in two steps, as if it was actually loading and computing something invisible.

Violentmonkey on Windows 10 Vivaldi 3 and Firefox 79, on Linux Firefox 68 and on Firefox for Android 68.

It's not necessarily a preference but I am used to use Violentmonkey since Opera presto.

**Comment by loujine** [comment]
Just realized that the script doesn't work if I'm not logged in. Rewrote the querySelectors to be more flexible, tell me if it works now. Looks fine for me on a new firefox profile with violentmonkey on linux

**Comment by jesus2099** [comment]
It works if I switch my FUNKEY CAA script off, actually! 👍

**Comment by loujine** [comment]
Uh. I can confirm, if FUNKEY is installed first the timeline fails with absolutely no message. If the timeline script is installed first it seem it works ok

**Comment by jesus2099** [comment]
It's the bigpics that conflicts.
I am currently modifying FUNKEY but am waiting for https://tickets.metabrainz.org/browse/CAA-122 ticket, first...
