### ISSUE TITLE
Wikidata: Autofill country is always Netherlands

### ISSUE THREAD

**Issue by ordinarygulp** [loujine/musicbrainz-scripts#7]
Since 8.15 update, any country, no matter what Wikidata lists, is filled into MB as Netherlands

Fixed by reverting this commit: https://github.com/loujine/musicbrainz-scripts/commit/9140f035aa5689bf7db1ea17c31c18c6d4cd63d7

**Comment by loujine** [comment]
I'm so stupid. Thanks, pushing a fix now
