### ISSUE TITLE
Wikidata: Plugin no longer shows on page with server update 2020-09-07

### ISSUE THREAD

**Issue by ordinarygulp** [loujine/musicbrainz-scripts#8]
After MB did this server update: [2020-09-07](https://blog.metabrainz.org/2020/09/07/musicbrainz-server-update-2020-09-07/), the wikidata link entry point on the side of edit artist page no longer appears.

**Comment by reosarevok** [comment]
I think https://github.com/loujine/musicbrainz-scripts/pull/9 fixes that

**Comment by loujine** [comment]
Looks fixed with reo's fixes, version 2020.9.8
